# Generated by Django 3.1.1 on 2020-09-19 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20200918_0908'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='has_size',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
